# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliwineApp', '0002_bottle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.RenameField(
            model_name='bottle',
            old_name='year',
            new_name='acidity',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='color',
        ),
        migrations.AddField(
            model_name='bottle',
            name='alcohol',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle',
            name='body',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle',
            name='flavour_intensity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle',
            name='sweetness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle',
            name='tannin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottle',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
