# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliwineApp', '0004_auto_20160506_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField()),
                ('aromaCharacteristic', models.CharField(max_length=2048)),
                ('sweetness', models.IntegerField()),
                ('acidity', models.IntegerField()),
                ('tanning', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('body', models.IntegerField()),
                ('flavourIntensity', models.IntegerField()),
                ('flavourCharacteristic', models.CharField(max_length=2048)),
                ('finish', models.IntegerField()),
                ('qualityLevel', models.IntegerField()),
            ],
        ),
    ]
