# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intelliwineApp', '0006_auto_20160530_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlevectorflavourandaroma',
            name='bottle_charac',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='intelliwineApp.BottleVectorCharacteristics'),
        ),
    ]
