# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelliwineApp', '0007_bottlevectorflavourandaroma_bottle_charac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlevectorflavourandaroma',
            name='bottle_charac',
        ),
    ]
