# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliwineApp', '0011_auto_20160617_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlevectorcharacteristics',
            name='bottle_foreign_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bottlevectorflavourandaroma',
            name='bottle_foreign_id',
            field=models.IntegerField(default=0),
        ),
    ]
