# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-20 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelliwineApp', '0013_user_uservectorcharacteristics_uservectorflavourandaroma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottledna',
            old_name='qualityLevel',
            new_name='quality_level',
        ),
        migrations.RenameField(
            model_name='bottlevectorcharacteristics',
            old_name='qualityLevel',
            new_name='quality_level',
        ),
        migrations.RenameField(
            model_name='uservectorcharacteristics',
            old_name='qualityLevel1',
            new_name='quality_level1',
        ),
        migrations.RenameField(
            model_name='uservectorcharacteristics',
            old_name='qualityLevel2',
            new_name='quality_level2',
        ),
        migrations.RenameField(
            model_name='uservectorcharacteristics',
            old_name='qualityLevel3',
            new_name='quality_level3',
        ),
        migrations.RenameField(
            model_name='uservectorcharacteristics',
            old_name='qualityLevel4',
            new_name='quality_level4',
        ),
        migrations.RenameField(
            model_name='uservectorcharacteristics',
            old_name='qualityLevel5',
            new_name='quality_level5',
        ),
        migrations.RenameField(
            model_name='uservectorcharacteristics',
            old_name='qualityLevel6',
            new_name='quality_level6',
        ),
    ]
