# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-20 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelliwineApp', '0014_auto_20160620_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='acidity1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='acidity2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='acidity3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='acidity4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='acidity5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='alcohol1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='alcohol2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='alcohol3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='alcohol4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='alcohol5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='body1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='body2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='body3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='body4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='body5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='finish1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='finish2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='finish3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='finish4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='finish5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='flavour_intensity1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='flavour_intensity2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='flavour_intensity3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='flavour_intensity4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='flavour_intensity5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='intensity1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='intensity2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='intensity3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='intensity4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='intensity5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='quality_level1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='quality_level2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='quality_level3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='quality_level4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='quality_level5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='quality_level6',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='sweetness1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='sweetness2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='sweetness3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='sweetness4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='sweetness5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='sweetness6',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='tannin1',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='tannin2',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='tannin3',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='tannin4',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='uservectorcharacteristics',
            name='tannin5',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
