# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-05 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelliwineApp', '0018_auto_20161201_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlevectorcharacteristics',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='bottlevectorcharacteristics',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='finish1',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='finish2',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='finish3',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='finish4',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='finish5',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='intensity1',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='intensity2',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='intensity3',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='intensity4',
        ),
        migrations.RemoveField(
            model_name='uservectorcharacteristics',
            name='intensity5',
        ),
    ]
